# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/best_att.pth'
  config: 'ckpt/end_to_end_config_sd0/best_att.pth'
data:
  corpus:
    name: 'TIMIT'
    dev_split: ['dev']
    test_split: ['test']
decode:
  beam_size: 20
  min_len_ratio: 0.01
  max_len_ratio: 0.07
  lm_path: 'ckpt/end_to_end_config_sd0/best_ppx.pth'
  lm_config: 'config/libri/lm_example.yaml'
  lm_weight: 0.5
  ctc_weight: 0.0
